version: '3'
services:
  rabbit:
    container_name: rabbit
    image: rabbitmq:management
    build: ./data/dockerfiles/rabbitmq
    ports:
      - 40002:5672
      - 40003:15672
    volumes:
      - rabbit_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmgr
      - RABBITMQ_DEFAULT_PASS=M9QWSRXAPZcw2SKu
  canal:
    container_name: canal
    image: niweisi/canal-server-deployer:v1.1.4
    volumes:
      - ./data/server/canal/canal.properties:/home/admin/canal-server/conf/canal.properties
      - ./data/server/canal/example/instance.properties:/home/admin/canal-server/conf/example/instance.properties
volumes:
  rabbit_data:
