version: '3'
services:
  nginx:
    container_name: nginx1.18.0
    image: nginx:1.18.0
    ports:
      - "80:80"
    volumes:
      - "./data/server/nginx/conf.d:/etc/nginx/conf.d"
      - "./data/wwwroot:/data/wwwroot"
  php7.3.19:
    container_name: php-fpm-7.3.19
#    image: php:7.3.19-fpm
    build: ./data/dockerfiles/php/7.3.19
    volumes:
      - "./data/wwwroot:/data/wwwroot"
  dnsmasq:
    container_name: dnsmasq
    image: jpillora/dnsmasq
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "5380:8080"
    environment:
      HTTP_USER: "admin"
      HTTP_PASS: "123456"
    logging:
      driver: json-file
      options:
        max-size: "200k" # 单个文件大小为200k
        max-file: "10" # 最多10个文件
    volumes:
      - "./data/server/dnsmasq/dnsmasq.conf:/etc/dnsmasq.conf" #文件需要提前生成
  mysql8.0.18:
    container_name: mysql8.0.18
    build: ./data/dockerfiles/mysql/8.0.18
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - mysql_data:/var/lib/mysql            # 挂载数据目录
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
      #  /usr/local/etc/redis/redis.conf
volumes:
  mysql_data:
