version: '3'
services:
  nginx:
    container_name: nginx1.18.0
    image: nginx:1.18.0
    ports:
      - "80:80"
    volumes:
      - "./data/server/nginx/conf.d:/etc/nginx/conf.d"
      - "./data/wwwroot:/data/wwwroot"
  php7.3.19:
    container_name: php-fpm-7.3.19
    image: niweisi/php-fpm:7.3.19
    #    build: ./data/dockerfiles/php/7.3.19
    volumes:
      - "./data/wwwroot:/data/wwwroot"
    ports:
      - "443:443"
  mysql8.0.18:
    container_name: mysql8.0.18
    build: ./data/dockerfiles/mysql/8.0.18
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - mysql_data_8.0.18:/var/lib/mysql            # 挂载数据目录
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
      #  /usr/local/etc/redis/redis.conf
#    restart: always # 自启动
#    depends_on:
#      - mysql # 此服务先启动
volumes:
  mysql_data_8.0.18:
