version: '3'
services:
  es01:
    image: elasticsearch:7.17.1
    container_name: es01
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms256m -Xmx256m"
      xpack.security.enabled: "true"
      ELASTIC_PASSWORD: "123456"
    volumes:
      - es_data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    restart: always
volumes:
  es_data01:
    driver: local
