version: '3'
services:
  hyperf:
    build: ./data/dockerfiles/hyperf
    container_name: hyperf
    ports:
      - "19501-19510:9501-9510"
    volumes:
      - "./data/wwwroot:/data/wwwroot"
    restart: always
    privileged: true
    user: root
    stdin_open: true
    tty: true

