version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    privileged: true
    environment:
      JENKINS_OPTS: "--prefix=/jenkins"
      JAVA_OPTS: "-Duser.timezone=Asia/Shanghai"
    volumes:
      - "/data/jenkins_home:/var/jenkins_home"
    ports:
      - 8080:8080
      - 50000:50000
    restart: always

# docker-compose logs jenkins
