version: '3.3'

services:
  mongodb1:
    image: mongo:4.2.21
    container_name: mongodb1
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    volumes:
      - /data/mongo/mongodb1/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - /mongo/mongodb1/data:/data/db
    ports:
      - 27017:27017
