version: '3'
services:
  mysql5.7:
    container_name: mysql5.7
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_ROOT_HOST: "%"
    volumes:
      - mysql_data_5.7:/var/lib/mysql            # 挂载数据目录
    restart: always # 自启动

volumes:
  mysql_data_5.7:
