version: "3.8"
services:
  nacos:
    hostname: nacos
    container_name: nacos
    image: nacos/nacos-server:v2.1.1
    ports:
      - "8848:8848"
      - "7848:7848"
      - "9848:9848"
      - "9849:9849"
      - "9555:9555"
    environment:
      - NACOS_SERVER_IP=192.168.171.60
      - NACOS_SERVERS=192.168.171.50:8848 192.168.171.60:8848
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=192.168.171.50
      - MYSQL_SERVICE_DB_NAME=nacos
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=123456
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      - TIME_ZONE=Asia/Shanghai
    restart: always
    user: root

