version: "3.7"
services:
  node20:
    container_name: node20
    image: node:20-alpine
#    build: ./data/dockerfiles/node20
    volumes:
      - "/data/wwwroot:/data/wwwroot"
      - "/data/proxy:/data/proxy"
    ports:
      - "6020-6030:6020-6030"
    restart: always
    tty: true
    environment:
      - HTTP_PROXY=http://172.26.64.1:1080
      - HTTPS_PROXY=http://172.26.64.1:1080
