version: '3'
services:
  npm:
    build: ./data/dockerfiles/npm
    container_name: npm
    tty: true
    environment:
      TOOL_NODE_FLAGS: --max_old_space_size=4096
    ports:
      - "3000-3010:3000-3010"
    volumes:
      - "/data/wwwroot:/data/wwwroot"

