version: '3'
services:
  php5.3.29:
    container_name: php-5.3.29
    image: php:5.3.29
    ports:
      - "9029:9029"
    volumes:
      - "./data/wwwroot:/data/wwwroot"
    restart: always # 自启动


