version: '3'
services:
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    restart: always
    ports:
      - '8001:8001'
    volumes:
      - /root/redisinsight:/db
